// Generated by CoffeeScript 1.4.0

import * as THREE from 'https://cdnjs.cloudflare.com/ajax/libs/three.js/87/three.min.js';

var D, aspect, camera, height, light, loader, material, renderer, scene, width;
D = 20;
camera = new THREE.OrthographicCamera(-D * aspect, D * aspect, D, -D, 1, 1000);

(function() {
    
  
    width = window.screen.width;
    height = window.screen.height;
    
    console.log(window.screen.width);
    console.log(window.screen.height);

    aspect = width / height;

    scene = new THREE.Scene();  

  
    renderer = new THREE.WebGLRenderer({
      alpha: true
    });
  
    renderer.setSize(width, height);
    document.body.appendChild(renderer.domElement);
  
    material = new THREE.MeshPhongMaterial({
      wireframe: true,
      color:0xf49700
    });
  
    light = new THREE.DirectionalLight(0xffffff, 1.1);
    light.position.set(10, 20, 15);
    scene.add(light);
  
    camera.position.set(20, 20, 20);
  
    camera.lookAt(new THREE.Vector3(0, 0, 0));
  
    camera.rotation.z = 5 / 6 * Math.PI;
  
    loader = new THREE.ColladaLoader();


  
    loader.load('https://triqui.cf/app/assets/test.dae', function(collada) {
      collada.scene.scale.set(0.1, 0.1, 0.1);
      scene.add(collada.scene);
      return renderer.render(scene, camera);
    });

    loader2 = new THREE.ColladaLoader();
    loader2.load('https://triqui.cf/app/assets/mesas.dae', function(collada) {
      collada.scene.scale.set(0.1, 0.1, 0.1);
      scene.add(collada.scene);
      return renderer.render(scene, camera);
    });

  }).call(this);